_wandb:
    value:
        cli_version: 0.28.0
        e:
            853f7h957sn4elhh0d8z2q3832v5s0eq:
                codePath: h:\customer-segment\notebooks\train.ipynb
                codePathLocal: train.ipynb
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "104856547328"
                        used: "74423517184"
                email: uyentran12348@gmail.com
                executable: h:\customer-segment\venv\Scripts\python.exe
                git:
                    commit: ec1f21b644c6f68a66aaa0d590c54d043addbfeb
                    remote: https://github.com/phguyen/customer-segment
                host: DESKTOP-EOKEKRT
                memory:
                    total: "8421998592"
                os: Windows-10-10.0.19045-SP0
                program: h:\customer-segment\notebooks\train.ipynb
                python: CPython 3.13.1
                root: h:\customer-segment\notebooks
                startedAt: "2026-07-14T15:38:44.199252Z"
                writerId: 853f7h957sn4elhh0d8z2q3832v5s0eq
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
            "4": 3.13.1
            "5": 0.28.0
            "8":
                - 1
                - 3
            "12": 0.28.0
            "13": windows-amd64
